# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Glip' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'
  rn_ex_path = '../node_modules/react-native-share-extension'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for Glip
  #pod 'react-native-share-extension', path: rn_ex_path
  
  target 'GlipTests' do
    inherit! :search_paths
    # Pods for testing
  end

  # react-native-maps dependencies
  #pod 'react-native-maps', path: rn_maps_path
  pod 'GoogleMaps'
 
end

target 'Glip-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Glip-tvOS

  target 'Glip-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MyShareEx' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyShareEx

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
